name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
          
      - name: Get the sources
        uses: actions/checkout@v2
        
      - name: Run cake
        shell: bash
        run: |
          dotnet tool install Cake.Tool --version 1.1.0 --global
          dotnet tool restore
          dotnet cake --target=Pack --verbosity=verbose
