name: Build, Pack & Publish

on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      - name: Get the sources
        uses: actions/checkout@v4
      - name: build, pack & publish
        shell: bash
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: |
          dotnet tool install Cake.Tool --version 1.1.0 --global
          dotnet tool restore
          dotnet cake --target=Pack --verbosity=verbose
          dotnet nuget push artifacts/packages/*.nupkg --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json --skip-duplicate